export const categorias = [
  { label: 'SALARIO', value: 'SALARIO', icon: 'cash-outline', color: '#2ecc71' },
  { label: 'AGUA', value: 'AGUA', icon: 'water-outline', color: '#3498db' },
  { label: 'LUZ', value: 'LUZ', icon: 'bulb-outline', color: '#f1c40f' },
  { label: 'SAUDE', value: 'SAUDE', icon: 'heart-outline', color: '#e74c3c' },
  { label: 'TRANSPORTES', value: 'TRANSPORTES', icon: 'bus-outline', color: '#9b59b6' },
  { label: 'ALUGUER', value: 'ALUGUER', icon: 'home-outline', color: '#e67e22' },
  { label: 'INTERNET', value: 'INTERNET', icon: 'wifi-outline', color: '#1abc9c' },
  { label: 'TELEMOVEIS', value: 'TELEMOVEIS', icon: 'phone-portrait-outline', color: '#34495e' },
  { label: 'ARD', value: 'ARD', icon: 'tv-outline', color: '#7f8c8d' },
  { label: 'SUPERMERCADO', value: 'SUPERMERCADO', icon: 'cart-outline', color: '#d35400' },
  { label: 'LEVANTAMENTOS', value: 'LEVANTAMENTOS', icon: 'wallet-outline', color: '#c0392b' },
  { label: 'TRANSFERENCIAS', value: 'TRANSFERENCIAS', icon: 'swap-horizontal-outline', color: '#8e44ad' },
  { label: 'BANCOS', value: 'BANCOS', icon: 'business-outline', color: '#2980b9' },
  { label: 'COMPRAS', value: 'COMPRAS', icon: 'basket-outline', color: '#27ae60' },
  { label: 'VIAGENS', value: 'VIAGENS', icon: 'airplane-outline', color: '#f39c12' },
  { label: 'COMER FORA', value: 'COMER FORA', icon: 'restaurant-outline', color: '#d35400' },
  { label: 'LAZER', value: 'LAZER', icon: 'game-controller-outline', color: '#16a085' },
  { label: 'PREMIO', value: 'PREMIO', icon: 'trophy-outline', color: '#f1c40f' },
  { label: 'DROGARIA', value: 'DROGARIA', icon: 'medkit-outline', color: '#c0392b' },
  { label: 'GASOLINA', value: 'GASOLINA', icon: 'car-sport-outline', color: '#2c3e50' }
]
