export const categorias = [
  { label: 'SALARIO', value: 'SALARIO' },
  { label: 'AGUA', value: 'AGUA' },
  { label: 'LUZ', value: 'LUZ' },
  { label: 'SAUDE', value: 'SAUDE' },
  { label: 'TRANSPORTES', value: 'TRANSPORTES' },
  { label: 'ALUGUER', value: 'ALUGUER' },
  { label: 'INTERNET', value: 'INTERNET' },
  { label: 'TELEMOVEIS', value: 'TELEMOVEIS' },
  { label: 'ARD', value: 'ARD' },
  { label: 'SUPERMERCADO', value: 'SUPERMERCADO' },
  { label: 'LEVANTAMENTOS', value: 'LEVANTAMENTOS' },
  { label: 'TRANSFERENCIAS', value: 'TRANSFERENCIAS' },
  { label: 'BANCOS', value: 'BANCOS' },
  { label: 'COMPRAS', value: 'COMPRAS' },
  { label: 'VIAGENS', value: 'VIAGENS' },
  { label: 'COMER FORA', value: 'COMER FORA' },
  { label: 'LAZER', value: 'LAZER' },
  { label: 'PREMIO', value: 'PREMIO' },
]
